config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup'
  }

  scope module: 'app' do

    root to: 'home#index'

    resources :templates, except: [:edit]
  end

  namespace :api do
    resources :templates do
      resources :messages, only: [:create]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  self.implicit_order_column = 'created_at'
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :template

  validates :template, presence: true
  validates :body, presence: true
  validates :from, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :to, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/template.rb
# Defines for an email template
# Email template are basically some templated content
# * subject
# * body
# Which you can afterward call by replacing its variables by real value
class Template < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slugged

  validates :name, presence: true, uniqueness: true
  validates :subject, presence: true
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default registrations modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/messages_controller.rb
# frozen_string_literal: true

module Api

  # Answers to every requests pointing to `/api/templates/:template_id/messages/`
  class MessagesController < ApiController

    # Does not bring added value compared to the default rails behavior but allows to test
    # http status code in tests instead of exceptions
    rescue_from ActiveRecord::RecordInvalid, with: -> { head :bad_request }

    def create

      result = Messages::Creation.call(
        template_ref: message_params[:template_id],
        from: message_params[:from],
        to: message_params[:to],
        context: message_params[:context].to_h
      )

      if result.failure?
        head :not_found
        return
      end

      message = result.built_message

      if message.valid?
        message.save!
        MessageMailer.prepare(message).deliver_later
        head :ok
      else
        render status: :bad_request, json: message.errors
      end

    end

    private

    def message_params
      params.permit(:template_id, :from, :to, context: {})
    end

  end
end

app/controllers/api_controller.rb
# frozen_string_literal: true

class ApiController < ActionController::API
end

app/controllers/app/home_controller.rb
# frozen_string_literal: true

module App

  # Controller in charge of displaying the home page
  class HomeController < ApplicationController
    def index; end
  end

end

app/controllers/app/templates_controller.rb
# frozen_string_literal: true

module App

  # Answers to every requests pointing to `/templates/*`
  class TemplatesController < ApplicationController
    before_action :authenticate_user!

    before_action :retrieve_template, only: %i[show update destroy]

    # GET /templates
    # GET /templates.json
    def index
      @templates = Templates::ListAll.execute.templates
    end

    # GET /templates/1
    # GET /templates/1.json
    def show; end

    # GET /templates/new
    def new
      @template = Template.new
    end

    # GET /templates/1/edit
    # def edit; end

    # POST /templates
    # POST /templates.json
    def create
      @template = Template.new(template_params)

      respond_to do |format|
        if @template.save
          format.html { redirect_to @template, notice: 'Template was successfully created.' }
          format.json { render :show, status: :created, location: @template }
        else
          format.html { render :new }
          format.json { render json: @template.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /templates/1
    # PATCH/PUT /templates/1.json
    def update
      respond_to do |format|
        if @template.update(template_params)
          format.html { redirect_to @template, notice: 'Template was successfully updated.' }
          format.json { render :show, status: :ok, location: @template }
        else
          format.html { render :edit }
          format.json { render json: @template.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /templates/1
    # DELETE /templates/1.json
    def destroy
      Templates::Delete.execute(template: @template)
      respond_to do |format|
        format.html { redirect_to templates_url, notice: 'Template was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def retrieve_template
      @template = Templates::FindOne.execute(template_ref: params[:id]).template
    end

    # Only allow a list of trusted parameters through.
    def template_params
      params.require(:template).permit(:name, :subject, :body)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
# Global helpers
module ApplicationHelper
  def page_title(title = nil)
    [title, 'TeaMail'].reject(&:blank?).join(' | ')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/app/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/app/templates/_form.html.slim
- content_for(:javascripts_post) do
  = javascript_pack_tag 'template-editor', 'data-turbolinks-track': 'reload'

- content_for(:stylesheets) do
  = stylesheet_pack_tag 'template-editor', 'data-turbolinks-track': 'reload'

= form_with model: @template, local: true, html: { class: 'ui form with-template-editor'.concat(@template.errors.any? ? ' error' : '') } do |f|
  - if @template.errors.any?
    .ui.error.message
      .header = "#{pluralize(@template.errors.count, "error")} prohibited this template from being saved:"
      ul
        - @template.errors.full_messages.each do |message|
          li = message
  .field.required class=('error' unless @template.errors[:name].empty?)
    = f.label :name
    = f.text_field :name
  .field.required class=('error' unless @template.errors[:subject].empty?)
    = f.label :subject
    = f.text_field :subject
  .field.required class=('error' unless @template.errors[:body].empty?)
    = f.label :body
    = f.hidden_field :body

  .template-editor == @template.body
  .actions = f.submit class: 'ui primary button'

app/views/app/templates/edit.html.slim
.ui.container
  h2=t('.title')

  == render 'form'

  => link_to t('show'), @template
  '|
  =< link_to t('back'), templates_path

app/views/app/templates/index.html.slim
- content_for(:title) do
  = t('.title')

.ui.container
  h2=t('.title')

  table.ui.celled.table
    thead
      tr
        th Name
        th API Id
        th Subject
        th colspan="2" Actions

    tbody
      - @templates.each do |template|
        tr
          td data-label="Name" = link_to template.name, template
          td data-label="API Id" = template.friendly_id
          td data-label="Subject" = template.subject
          td = link_to 'Show', template
          td = link_to 'Destroy', template, data: { confirm: 'Are you sure?' }, method: :delete

  = link_to new_template_path, class: 'ui primary button' do
    i.plus.icon
    = t('.create_new')

app/views/app/templates/new.html.slim
.ui.container
  h2=t('.title')

  == render 'form'

  = link_to t('back'), templates_path

app/views/app/templates/show.html.slim
.ui.container
  h2=t('.title')

  == render 'form'

= link_to 'Back', templates_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1"
    title
      = page_title(yield :title)

    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'styles', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'styles', 'data-turbolinks-track': 'reload'
    = yield :stylesheets
    = yield :javascripts
  body
    nav.ui.fixed.main.menu.inverted
      = link_to templates_path, class: 'item' do
        = t('.menu.my_templates')

    - if notice
      #notice.flash = notice
    - if alert
      #alert.flash = alert

    #main-container
      = yield

    = yield :javascripts_post